# Generated by Django 5.2.8 on 2025-11-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='estoque',
        ),
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, default='dem decridao'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
