# Generated by Django 5.2.8 on 2025-11-23 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0002_remove_produto_criado_em_remove_produto_estoque_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=500),
        ),
    ]
