# Generated by Django 5.2.8 on 2025-11-23 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0004_alter_produto_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.TextField(blank=True),
        ),
    ]
