# Generated by Django 5.2.8 on 2025-11-24 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0005_alter_produto_imagem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='imagem_base64',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
