# Generated by Django 5.2.8 on 2025-11-25 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_server', '0006_produto_estoque_produto_imagem_base64_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem_base64',
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
